#ifndef __CHARACTER_INFO_ENUM_H__
#define __CHARACTER_INFO_ENUM_H__

/* Auto Generated by Character.xlsm */

class CharacterInfoEnum {
public:
    const static CharacterInfoEnum ALIAS;
    const static CharacterInfoEnum SPRITE_BASE;
    const static CharacterInfoEnum SPRITE_INITIAL;
    const static CharacterInfoEnum CLASS;
    const static CharacterInfoEnum ARMOR;
    const static CharacterInfoEnum WEAPON;
    const static CharacterInfoEnum AGE;
    inline int getValue() { return value; }
private:
    int value;
    CharacterInfoEnum(int i) : value(i) {}
};

#endif //__CHARACTER_INFO_ENUM_H__
