#ifndef __CHARACTER_INFO_H__
#define __CHARACTER_INFO_H__

/* Auto Generated by Character.xlsm */

enum CharacterInfoEnum {
    ALIAS = 0,
    SPRITE = 1,
    CLASS = 2,
    ARMOR = 3,
    WEAPON = 4,
};

#endif //__CHARACTER_INFO_ENUM_H__
