/* Auto Generated by Character.xlsm */
 #include "CharacterInfoEnum.h" 
const CharacterInfoEnum CharacterInfoEnum::ALIAS = CharacterInfoEnum(0);
const CharacterInfoEnum CharacterInfoEnum::SPRITE_BASE = CharacterInfoEnum(1);
const CharacterInfoEnum CharacterInfoEnum::SPRITE_INITIAL = CharacterInfoEnum(2);
const CharacterInfoEnum CharacterInfoEnum::CLASS = CharacterInfoEnum(3);
const CharacterInfoEnum CharacterInfoEnum::ARMOR = CharacterInfoEnum(4);
const CharacterInfoEnum CharacterInfoEnum::WEAPON = CharacterInfoEnum(5);
const CharacterInfoEnum CharacterInfoEnum::AGE = CharacterInfoEnum(6);
