/* Auto Generated by Character.xlsm */
 #include "EnemyStatsEnum.h" "
const EnemyStatsEnum EnemyStatsEnum::NAME = EnemyStatsEnum(0);
const EnemyStatsEnum EnemyStatsEnum::LEVEL = EnemyStatsEnum(1);
const EnemyStatsEnum EnemyStatsEnum::HP = EnemyStatsEnum(2);
const EnemyStatsEnum EnemyStatsEnum::APOW = EnemyStatsEnum(3);
const EnemyStatsEnum EnemyStatsEnum::MPOW = EnemyStatsEnum(4);
const EnemyStatsEnum EnemyStatsEnum::ADEF = EnemyStatsEnum(5);
const EnemyStatsEnum EnemyStatsEnum::MDEF = EnemyStatsEnum(6);
const EnemyStatsEnum EnemyStatsEnum::SPEED = EnemyStatsEnum(7);
const EnemyStatsEnum EnemyStatsEnum::DROP_1 = EnemyStatsEnum(8);
const EnemyStatsEnum EnemyStatsEnum::DROP_2 = EnemyStatsEnum(9);
const EnemyStatsEnum EnemyStatsEnum::DROP_3 = EnemyStatsEnum(10);
const EnemyStatsEnum EnemyStatsEnum::DROP_RATE_1 = EnemyStatsEnum(11);
const EnemyStatsEnum EnemyStatsEnum::DROP_RATE_2 = EnemyStatsEnum(12);
const EnemyStatsEnum EnemyStatsEnum::DROP_RATE_3 = EnemyStatsEnum(13);
const EnemyStatsEnum EnemyStatsEnum::GOLD_DROP = EnemyStatsEnum(14);
const EnemyStatsEnum EnemyStatsEnum::SPRITE = EnemyStatsEnum(15);
const EnemyStatsEnum EnemyStatsEnum::SKILL_1 = EnemyStatsEnum(16);
const EnemyStatsEnum EnemyStatsEnum::SKILL_2 = EnemyStatsEnum(17);
const EnemyStatsEnum EnemyStatsEnum::SKILL_3 = EnemyStatsEnum(18);
