#ifndef __ENEMY_STATS_ENUM_H__
#define __ENEMY_STATS_ENUM_H__

/* Auto Generated by Character.xlsm */

class EnemyStatsEnum {
public:
    const static EnemyStatsEnum NAME;
    const static EnemyStatsEnum LEVEL;
    const static EnemyStatsEnum HP;
    const static EnemyStatsEnum APOW;
    const static EnemyStatsEnum MPOW;
    const static EnemyStatsEnum ADEF;
    const static EnemyStatsEnum MDEF;
    const static EnemyStatsEnum SPEED;
    const static EnemyStatsEnum DROP_1;
    const static EnemyStatsEnum DROP_2;
    const static EnemyStatsEnum DROP_3;
    const static EnemyStatsEnum DROP_RATE_1;
    const static EnemyStatsEnum DROP_RATE_2;
    const static EnemyStatsEnum DROP_RATE_3;
    const static EnemyStatsEnum GOLD_DROP;
    const static EnemyStatsEnum SPRITE;
    const static EnemyStatsEnum SKILL_1;
    const static EnemyStatsEnum SKILL_2;
    const static EnemyStatsEnum SKILL_3;
    inline int getValue() { return value; }
private:
    int value;
    EnemyStatsEnum(int i) : value(i) {}
};

#endif //__ENEMY_STATS_ENUM_H__
