/* Auto Generated by Characters.xlsm */
 #include "EnemyEnum.h" 
const EnemyEnum EnemyEnum::PORK = EnemyEnum(0);
const EnemyEnum EnemyEnum::NUM_ENEMIES = EnemyEnum(1);
EnemyEnum EnemyEnum::getEnemyByIndex( int index ) {
    switch(index) {
    case 0:
        return EnemyEnum::PORK;
        break;
    default: return NUM_ENEMIES;
    }
}
