/* Auto Generated by Items.xlsm */
 #include "ItemStatEnum.h" 
const ItemStatEnum ItemStatEnum::NAME = ItemStatEnum(0);
const ItemStatEnum ItemStatEnum::DESCRIPTION = ItemStatEnum(1);
const ItemStatEnum ItemStatEnum::STACKS = ItemStatEnum(2);
const ItemStatEnum ItemStatEnum::USE = ItemStatEnum(3);
const ItemStatEnum ItemStatEnum::USE_DESCRIPTION = ItemStatEnum(4);
const ItemStatEnum ItemStatEnum::EQUIP = ItemStatEnum(5);
const ItemStatEnum ItemStatEnum::WEAPON_TYPE = ItemStatEnum(6);
const ItemStatEnum ItemStatEnum::ARMOR_TYPE = ItemStatEnum(7);
const ItemStatEnum ItemStatEnum::ITEM_TYPE = ItemStatEnum(8);
