#ifndef __ITEM_ENUM_H__
#define __ITEM_ENUM_H__

/* Auto Generated by Items.xlsm */

enum ItemEnum {
    PLAIN_WATER = 0,
    POTION = 1,
    SWORD = 2,
    CHAINMAIL = 3,
    NUM_ITEMS = 4,
};

#endif //__ITEM_ENUM_H__
