#ifndef __ITEM_STAT_ENUM_H__
#define __ITEM_STAT_ENUM_H__

/* Auto Generated by Items.xlsm */

class ItemStatEnum {
public:
    const static ItemStatEnum NAME;
    const static ItemStatEnum DESCRIPTION;
    const static ItemStatEnum STACKS;
    const static ItemStatEnum USE;
    const static ItemStatEnum USE_DESCRIPTION;
    const static ItemStatEnum EQUIP;
    const static ItemStatEnum WEAPON_TYPE;
    const static ItemStatEnum ARMOR_TYPE;
    const static ItemStatEnum ITEM_TYPE;
    inline int getValue() { return value; };
private:
    int value;
    ItemStatEnum(int i) : value(i) {}
};

#endif //__ITEM_STAT_ENUM_H__
