/* Auto Generated by Items.xlsm */
 #include "ItemEnum.h" 
const ItemEnum ItemEnum::EMPTY = ItemEnum(0);
const ItemEnum ItemEnum::PLAIN_WATER = ItemEnum(1);
const ItemEnum ItemEnum::CHILI = ItemEnum(2);
const ItemEnum ItemEnum::DASHI = ItemEnum(3);
const ItemEnum ItemEnum::ITEM_1 = ItemEnum(4);
const ItemEnum ItemEnum::ITEM_2 = ItemEnum(5);
const ItemEnum ItemEnum::ITEM_3 = ItemEnum(6);
const ItemEnum ItemEnum::ITEM_4 = ItemEnum(7);
const ItemEnum ItemEnum::ITEM_5 = ItemEnum(8);
const ItemEnum ItemEnum::ITEM_6 = ItemEnum(9);
const ItemEnum ItemEnum::SWORD = ItemEnum(10);
const ItemEnum ItemEnum::KATANA = ItemEnum(11);
const ItemEnum ItemEnum::SPEAR = ItemEnum(12);
const ItemEnum ItemEnum::WEAPON1 = ItemEnum(13);
const ItemEnum ItemEnum::WEAPON2 = ItemEnum(14);
const ItemEnum ItemEnum::WEAPON3 = ItemEnum(15);
const ItemEnum ItemEnum::WEAPON4 = ItemEnum(16);
const ItemEnum ItemEnum::WEAPON5 = ItemEnum(17);
const ItemEnum ItemEnum::WEAPON6 = ItemEnum(18);
const ItemEnum ItemEnum::WEAPON7 = ItemEnum(19);
const ItemEnum ItemEnum::WEAPON8 = ItemEnum(20);
const ItemEnum ItemEnum::WEAPON9 = ItemEnum(21);
const ItemEnum ItemEnum::T_SHIRT = ItemEnum(22);
const ItemEnum ItemEnum::HIDE_ARMOR = ItemEnum(23);
const ItemEnum ItemEnum::CHAINMAIL = ItemEnum(24);
const ItemEnum ItemEnum::NUM_ITEMS = ItemEnum(25);
ItemEnum ItemEnum::getItemByIndex( int index ) {
    switch(index) {
    case 0:
        return ItemEnum::EMPTY;
        break;
    case 1:
        return ItemEnum::PLAIN_WATER;
        break;
    case 2:
        return ItemEnum::CHILI;
        break;
    case 3:
        return ItemEnum::DASHI;
        break;
    case 4:
        return ItemEnum::ITEM_1;
        break;
    case 5:
        return ItemEnum::ITEM_2;
        break;
    case 6:
        return ItemEnum::ITEM_3;
        break;
    case 7:
        return ItemEnum::ITEM_4;
        break;
    case 8:
        return ItemEnum::ITEM_5;
        break;
    case 9:
        return ItemEnum::ITEM_6;
        break;
    case 10:
        return ItemEnum::SWORD;
        break;
    case 11:
        return ItemEnum::KATANA;
        break;
    case 12:
        return ItemEnum::SPEAR;
        break;
    case 13:
        return ItemEnum::WEAPON1;
        break;
    case 14:
        return ItemEnum::WEAPON2;
        break;
    case 15:
        return ItemEnum::WEAPON3;
        break;
    case 16:
        return ItemEnum::WEAPON4;
        break;
    case 17:
        return ItemEnum::WEAPON5;
        break;
    case 18:
        return ItemEnum::WEAPON6;
        break;
    case 19:
        return ItemEnum::WEAPON7;
        break;
    case 20:
        return ItemEnum::WEAPON8;
        break;
    case 21:
        return ItemEnum::WEAPON9;
        break;
    case 22:
        return ItemEnum::T_SHIRT;
        break;
    case 23:
        return ItemEnum::HIDE_ARMOR;
        break;
    case 24:
        return ItemEnum::CHAINMAIL;
        break;
    default: return EMPTY;
    }
}
