#ifndef __ITEM_ENUM_H__
#define __ITEM_ENUM_H__

/* Auto Generated by Items.xlsm */

enum ItemEnum {
    EMPTY = 0,
    PLAIN_WATER = 1,
    CHILI = 2,
    DASHI = 3,
    ITEM_1 = 4,
    ITEM_2 = 5,
    ITEM_3 = 6,
    ITEM_4 = 7,
    ITEM_5 = 8,
    ITEM_6 = 9,
    SWORD = 10,
    KATANA = 11,
    SPEAR = 12,
    WEAPON1 = 13,
    WEAPON2 = 14,
    WEAPON3 = 15,
    WEAPON4 = 16,
    WEAPON5 = 17,
    WEAPON6 = 18,
    WEAPON7 = 19,
    WEAPON8 = 20,
    WEAPON9 = 21,
    T_SHIRT = 22,
    HIDE_ARMOR = 23,
    CHAINMAIL = 24,
    NUM_ITEMS = 25,
};

#endif //__ITEM_ENUM_H__
