#ifndef __STATS_ENUM_H__
#define __STATS_ENUM_H__

/* Auto Generated by Character.xlsm */

enum StatsEnum {
    LEVEL = 0,
    HP = 1,
    APOW = 2,
    MPOW = 3,
    ADEF = 4,
    MDEF = 5,
};

#endif //__STATS_ENUM_H__
