/* Auto Generated by Character.xlsm */
 #include "StatsEnum.h" "
const StatsEnum StatsEnum::LEVEL = StatsEnum(0);
const StatsEnum StatsEnum::HP = StatsEnum(1);
const StatsEnum StatsEnum::APOW = StatsEnum(2);
const StatsEnum StatsEnum::MPOW = StatsEnum(3);
const StatsEnum StatsEnum::ADEF = StatsEnum(4);
const StatsEnum StatsEnum::MDEF = StatsEnum(5);
const StatsEnum StatsEnum::SPEED = StatsEnum(6);
