#ifndef __STATS_ENUM_H__
#define __STATS_ENUM_H__

/* Auto Generated by Character.xlsm */

class StatsEnum {
public:
    const static StatsEnum LEVEL;
    const static StatsEnum HP;
    const static StatsEnum APOW;
    const static StatsEnum MPOW;
    const static StatsEnum ADEF;
    const static StatsEnum MDEF;
    const static StatsEnum SPEED;
    inline int getValue() { return value; }
private:
    int value;
    StatsEnum(int i) : value(i) {}
};

#endif //__CHARACTER_INFO_ENUM_H__
